# nodeLinker: pnp

# yarnPath: .yarn/releases/yarn-4.1.1.cjs

packageExtensions:
  '@storybook/nextjs@*':
    dependencies:
      'webpack': '*'
  '@chromatic-com/storybook@*':
    dependencies:
      '@storybook/client-logger': '*'
      '@storybook/core-events': '*'
